project_id = "psyiqnjxahablwaictaq"

[functions.ai-summary]
verify_jwt = false

[functions.generate-news-description]
verify_jwt = false

[functions.generate-brief]
verify_jwt = false

[functions.extract-image-text]
verify_jwt = false