// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psyiqnjxahablwaictaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzeWlxbmp4YWhhYmx3YWljdGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMjQxNDcsImV4cCI6MjA4NTgwMDE0N30.gb21aOfaC72fyn6K1VFxNMNfh-G1SZri1XaF-Sgy88Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});